### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by nlt2390**
rnpm already merged to react-native 0.29.2+

### CODE REVIEW

**Comment by 4ian** [comment]
Thanks for the PR :) Do you think the `gradle` part is really needed though?

**Comment by nlt2390** [comment]
@4ian Yes it is, `react-native run-android` will give errors without it.

**Comment by 4ian** [comment]
That's really strange :O I thought I made test with RN 0.31 without having such a problem. Are you making your tests on a new project or an existing one?

**Comment by nlt2390** [comment]
I installed on my existing project. It's weird that after running `react-native link`, nothing was added to my `settings.gradle`.

**Comment by cfogelklou** [comment]
I didn't need to do the .gradle change either, and I'm on 0.32.

**Comment by nlt2390** [comment]
Guess I'm gonna remove it

**Comment by 4ian** [comment]
Sounds good :)

**Pull request merged**
