### PR TITLE
Update Android SDK Build Tools version

### PR DESCRIPTION
**Pull request by lucasbento**

### CODE REVIEW

**Comment by 4ian** [comment]
Hey @lucasbento thanks for the PR :)
Out of curiosity, does this bring improvement to the build time or on anything else?
Is there any risk of incompatibility with other React Native modules or React Native itself? The [Getting Started documentation](https://facebook.github.io/react-native/docs/getting-started.html) still tell developers to install `Android SDK Build-Tools 23.0.1` :)

**Comment by 4ian** [comment]
@lucasbento Any new insights about this? :)

**Comment by lucasbento** [comment]
@4ian: sorry but no, haven't had any time to work on this since I already finished the project I was working on.

cc @sibelius, maybe have something about this.

**Comment by sibelius** [comment]
this could help https://blog.bam.tech/developper-news/boost-compilation-time-react-native-android-app-latest-android-build-tools

I wrote a script to upgrade all deps to android 25 as well

https://gist.github.com/sibelius/0a5403a2b5e9dd9ed9d98078a1523a18

**Comment by 4ian** [comment]
@sibelius Nice :) You could contact @Minishlink which wrote our article about using the latest android build tools.
I'm afraid upgrading the build tools in this module would force anyone using it to have these build tools installed.. It's maybe to earlier to do that? What do you think @sibelius @Minishlink?

**Comment by Minishlink** [comment]
For libraries and modules, it's indeed best to align with the versions on the [React Native getting started guide](https://facebook.github.io/react-native/docs/getting-started.html).
For your apps, you can workaround the issue by using the aforementioned [article](https://blog.bam.tech/developper-news/boost-compilation-time-react-native-android-app-latest-android-build-tools) or @sibelius' [script](https://gist.github.com/sibelius/0a5403a2b5e9dd9ed9d98078a1523a18)

**Pull request closed without merging**
