### PR TITLE
feat: add different resize modes and onlyScaleDown options

### PR DESCRIPTION
**Pull request by pxpeterxu**
### Motivation

I was resizing images for a Tensorflow model, which required images to be exactly 224x224, rather than some size smaller than 224.

### Changes

- Add `options.mode` option to `createResizedImage` with similar values to those for [react-native <Image>'s resizeMode](https://reactnative.dev/docs/image#resizemode)
  - `contain`: existing behavior: will resize image to be fit within `width`/`height`, preserving the aspect ratio
  - `cover`: resize image to have one dimension be `width`/`height`, and the other be bigger, preserving the aspect ratio
  - `stretch`: will resize to _exactly_ the width/height given, ignoring the aspect ratio
- Add `options.onlyScaleDown` for cases where we only want the resulting image to be smaller or the same size as the original
- Updated docs
- Got the example app to build on Android and iOS again and have more options for testing

### Testing

Tested using an actual Android device (Pixel 3a, Android 10) and iOS Simulator (iPhone 8, iOS 13.3)

#### Android

Android screen capture

#### iOS

iOS screen capture

### CODE REVIEW

**Comment by pxpeterxu** [comment]
@PierreCapo I just updated the code to be rebased on the latest master and conflict-free! Let me know if you might be able to take a look here; I'd really appreciate it 😀

**Comment by PierreCapo** [comment]
Hello @pxpeterxu sorry I'm super sad for not having reviewed this pr sooner. And honestly it's a pretty astonishing PR, thank you so much for having taken thee time to open it. I'll try to review it and make a release this week

**Comment by pxpeterxu** [comment]
Hey, no worries @PierreCapo! Thanks for writing a great library in the first place; it works a lot better than `expo-image-manipulator`'s resizer, especially on Android

**Comment by crobinson42** [comment]
This is a good PR!

**Comment by hsource** [comment]
@PierreCapo - is there any chance of getting this merged still? Let me know! I'm using a patch of this PR in the meantime

**Comment by PierreCapo** [comment]
@hsource I forgot about this PR, but yes please I'd need some help to review this PR. I didn't write this lib, I'm just managing it and my knowledges in Java are pretty terrible. I'm a bit better in Objective-C but I'd need some help there too. 

By the way, I think with this big PR merged, we could start migrating from Obj-C to Swift without losing too much work in progress, since at bam we are mostly using Swift (in which I'm far more comfortable with too).
So yeah, merging this PR would be a great milestone.

@cristianoccazinsp I know you are pretty familiar with the codebase, if you got time, could you help reviewing this PR too please?

@hsource did you face any issue while using the fork?

Waiting for your green lights guys

**Comment by hsource** [comment]
@PierreCapo - heads up, the fork has been running well on our app. I ran the example app and looked through the code, and honestly this looks like a really great change. I recommend just pulling this!

**Comment by PierreCapo** [comment]
I've tested and I've found nothing wrong on my side too 👍

Merged and release under `1.4.0`.
Thanks a lot to everyone involved and particularly to @pxpeterxu and @hsource for this super nice improvement. Also thanks for spending time improving the example app and the readme 😃

Have a good day!

**Comment by cristianoccazinsp** [comment]
Lovely PR! I will be giving a try within the following days (I also forgot about it for a long time :() and will provide feedback if anything breaks. Our app heavily depends on image processing so I think it will be a good test.

**Comment by cristianoccazinsp** [comment]
@PierreCapo @pxpeterxu  I was just trying this update.  Looks like after upgrading to 1.4.0, all my image resizing are suddenly not preserving aspect ratio on Android. Testing on iOS shortly, but the update was a breaking one for our app.

The following shows the before and after without any code changes (just a lib update). Looks like the defaults are not appropriate to preserve the previous behaviour:

image

**Comment by pxpeterxu** [comment]
@cristianoccazinsp I can take a look at this! Which mode were you using (stretch, cover, contain), and was it an upsize or downsize?

**Comment by cristianoccazinsp** [comment]
@pxpeterxu  I did not set any mode at all, just default options. I was expecting the updates to be non-breaking.

**Comment by cristianoccazinsp** [comment]
Any luck reviewing this? The update has been live for some time now and there was also another report about the issue here: https://github.com/bamlab/react-native-image-resizer/issues/265

**Pull request merged**
