### PR TITLE
Resizing with orientation

### PR DESCRIPTION
**Pull request by zubricky**
I was running into some issues sizing images from the camera, they would already be rotated based on the camera/ExifInterface orientation.

Created the method `createResizedImageUsingOrientation` which takes the same parameters, but looks at the image's ExifInterface orientation, so if no rotation is passed, the image will be "upright" based on how you took it.

Haven't used the library on iOS yet, so not sure if that platform has the same issue.

### CODE REVIEW

**Comment by 4ian** [comment]
Hey @zubricky, sorry for answering so late! Thanks for contributing, I'll give your PR a try this week-end and merge it if everything looks ok :)

**Comment by dcworldwide** [comment]
@zubricky Is your issue by chance related to Galaxy S5?

**Comment by zubricky** [comment]
@dcworldwide I was testing on an S5 simulator as well as my personal S4 phone and was seeing the issue on both. Is the issue limited to a few phones/os versions?

**Comment by dcworldwide** [comment]
@zubricky Assuming you are using https://github.com/lwansbrough/react-native-camera? I'm not sure if the issue is device specific or not. I've just noticed a few galaxy testers raise this issue though. This is a good fix, as it's use is generic, but I think there should be a fix upstream too in the camera lib,

**Comment by stoffern** [comment]
Rotation error is on Samsung S6 to.
if you capture or select from camera roll the same error applies

**Comment by stoffern** [comment]
@zubricky using captured images works, but if you load local images it errors:
E/JHEAD: can't open '/content:/media/external/images/media/1706'

**Comment by 4ian** [comment]
@stoffern For loading local images, make sure you use latest version of the react-native-image-resizer. Also, try the sample included here: https://github.com/bamlab/react-native-image-resizer/tree/master/example

It loads and resizes an image from the camera roll. It works well on Android for me :)

**Comment by stoffern** [comment]
@4ian already tested all of that.
I am giving it a total rewrite to fix the issues for Samsung series. This is a noted bug from Android and Samsung.

**Comment by stoffern** [comment]
This is related to the issue.
http://stackoverflow.com/a/23687300

**Comment by stoffern** [comment]
Problem found.
When selecting from the image gallery the path is not correct.
it should use the content resolver to find real path for this.

I will apply a new pull to fix this issue now

**Comment by stoffern** [comment]
I think this PR can be closed :smile:

**Comment by 4ian** [comment]
I think too, orientation has been handled by other PR/changes since this PR was made. :)

**Pull request closed without merging**
