### PR TITLE
Update RCTImageResizer.m

### PR DESCRIPTION
**Pull request by Psiiirus**
new up to date PR for https://github.com/bamlab/react-native-image-resizer/pull/160

I'm also extended the /example project to be useable for development and unf. i found out that this still blocks the UI. Any clue why?

### CODE REVIEW

**Comment by PierreCapo** [comment]
@Psiiirus Can you confirm we can close https://github.com/bamlab/react-native-image-resizer/pull/160  and use that PR instead ?

**Comment by Psiiirus** [comment]
Yeah I think so.

**Comment by cristianoccazinsp** [comment]
Can you guys confirm/tested that the following lines are no longer needed?

```
if ([path hasPrefix:@"data:"] || [path hasPrefix:@"file:"]) {
                NSURL *imageUrl = [[NSURL alloc] initWithString:path];
                image = [UIImage imageWithData:[NSData dataWithContentsOfURL:imageUrl]];
            } else {
                image = [[UIImage alloc] initWithContentsOfFile:path];
            }
```

Do files and data: schemas load fine with `loadImageWithURLRequest` ?

**Comment by Psiiirus** [comment]
@cristianoccazinsp if i remember correct did tests with base64 and file urls which where working fine not but i cant remember if i tested all kinds of asset-url-types, sorry

**Pull request merged**
