### PR TITLE
Implement http/https remote images for Android.

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
Implement remote (http/https) image loading for Android. iOS already support this.

The implementation is quite straight forward, although I wonder if React Native has a similar helper like the iOS one to load remote images. I couldn't find any, so cool features like caching won't work on Android.

Should close https://github.com/bamlab/react-native-image-resizer/issues/255 and https://github.com/bamlab/react-native-image-resizer/issues/245

### CODE REVIEW

**Comment by cristianoccazinsp** [comment]
Thoughts? Any chance to get this merged? Looks like XCode 12 (ios 14) is also wrecking havoc on most RN native modules and a podspec file upgrade is needed. Would be good to get this and the podspec fix merged asap.

**Comment by PierreCapo** [comment]
Sorry I totally forgot that PR...
Looks good to me, thank you as always @cristianoccazinsp 🚀

**Comment by PierreCapo** [comment]
@cristianoccazinsp I'm not working on a react-native project right now, and I'm not aware there are some issues with pods, looking at it now.

**Comment by PierreCapo** [comment]
Ok, from what I've read, only this change was needed: https://github.com/bamlab/react-native-image-resizer/pull/258
I don't have XCode 12 on my machine, so I can't double check, do you know if only this change was needed

I've just released react-native-image-resizer v1.3.0 with your PR merged and the pod changed aforementioned. Thanks a lot for the information about the pod issue.
Have a good day!

**Comment by cristianoccazinsp** [comment]
@PierreCapo thanks! Yes, I believe the only required change was the podspec update.

**Pull request merged**
