### PR TITLE
Remove deprecated method for RN 0.47 compat

### PR DESCRIPTION
**Pull request by forki**
The component doesn't compile in RN 0.47-rc5 - discussion at https://github.com/facebook/react-native/issues/15232

### CODE REVIEW

**Comment by sibelius** [comment]
I think it is better to just remove the @ override

much like this one https://github.com/idehub/react-native-google-analytics-bridge/pull/156/files

@bamlab can we get this in?

**Comment by 4ian** [comment]
Merged the fix remove the @override annotation. Can you confirm this is working on both 0.47 and pre-0.47 versions of React Native?

**Comment by pdavid0** [comment]
Fresh install 
```
>yarn add react-native-image-resizer
success Saved 1 new dependencies.
├─ react-native-image-resizer@0.1.1
```

`@Override` is still present in `ImageResizerPackage.java`

**Comment by 4ian** [comment]
Yep, I'll publish a new release today to fix this issue! Thanks for confirming that things work with master branch :)

**Comment by 4ian** [comment]
Done! :) Closing this issue now as problem is solve.

**Pull request closed without merging**
