### PR TITLE
Output path fix + orientation fix

### PR DESCRIPTION
**Pull request by stoffern**

### CODE REVIEW

**Comment by stoffern** [comment]
Propper orientation for Samsung and some Android devices.
Problem: Portrait images does not have correct rotation.
This also applies to images from device gallery.

This Orientation fix closes the impropper pull request: https://github.com/bamlab/react-native-image-resizer/pull/5

Tested on:
Samsung S4, Samsung S6

@dcworldwide looking for this? can you please test it?
@4ian Can you follow up this merge?

**Comment by dcworldwide** [comment]
I'll test it out early next week, thanks @stoffern :+1:

**Comment by 4ian** [comment]
Hey @stoffern, thanks for the PR! I've been able to reproduce the orientation issue on a Galaxy S6 but had not time to investigate to find a solution! I'll test it out this PR this week-end :)

Thanks for the follow up! If I forgot to answer until the end of the week, please ping me ;)

**Comment by stoffern** [comment]
Hi,
I have tested thisone and it works well on my devices.
Altho it seems like it is abit slow when trying to resolve realpath.

Looking into it.

cc @4ian

**Comment by stoffern** [comment]
status?
cc @4ian @dcworldwide

**Comment by 4ian** [comment]
Trying it now on Android and merging it if there are no issues! :)

**Comment by 4ian** [comment]
Looks good to me :) Thanks again for the PR!

**Pull request merged**
