### PR TITLE
prepare /example project for local development

### PR DESCRIPTION
**Pull request by Psiiirus**
- removed react-native-image-resizer package.json dependency and extended metro.config.js to use local version
- iOS: added local react-native-image-resizer path to Podfile to load correct iOS source files.

### CODE REVIEW

**Comment by Psiiirus** [comment]
FYI: The image is not stolen it's mine and free for use :-)

**Comment by PierreCapo** [comment]
Thanks for the PR @Psiiirus 
Point 1 with metro is awesome, thanks a lot for it.
I'm not sure about point 2. Why removing CameraRoll ? It allows to have a share implementation for android and iOS to get an image.

**Comment by Psiiirus** [comment]
> Thanks for the PR @Psiiirus
> Point 1 with metro is awesome, thanks a lot for it.
> I'm not sure about point 2. Why removing CameraRoll ? It allows to have a share implementation for android and iOS to get an image.

You're welcome :)

Well I did not remove the cameraRoll lib at it self i just removed the usage to have a more predictable test scenario but I can comment it back in if you like

**Comment by PierreCapo** [comment]
Well maybe I've missed something, but with those changes as it is, you should only be able to test on iOS and not on Android.

To merge the PR, I would:
- Keep the metro change you made
- Keep the massResize implementation (good idea)
- Remove the hardcoded image in iOS native side, and instead use CameraRoll that allows us to have one way to generate images for both iOS and Android at the same time. Also it seems to stick more to a "react-native" approach, so potentially easier to reproduce some bugs reported by user on this repo.

**Comment by Psiiirus** [comment]
Going to implement the points later but I am not Able to do this till Sunday ;)

BTW the hardcoded image should also work on Android. I’ve added this do have a similar base on Android and iOS but I will remove it, no problem.

**Comment by PierreCapo** [comment]
I've reused part of the code in this pr to use the local rn-image-resizer as dependency. Thanks for the pr! 👍

**Pull request closed without merging**
