### PR TITLE
Updated the `generateFilePath()`

### PR DESCRIPTION
**Pull request by ulentini**
Updated the `generateFilePath()` method to accept paths on cache directory. It also generate new files on documents directory, to be consistent with the rest of the method behavior.

Discussion: #90

### CODE REVIEW

**Comment by Minishlink** [comment]
Is this a breaking change?

**Comment by ulentini** [comment]
The only change that could be (maybe) considered _breaking_ is the default directory used to store files.
With this PR it changes from Cache directory to Document directory.

**Comment by Biplovkumar** [comment]
Not generated valid path,when output path is not given in iOS,throwing error.

**Comment by ulentini** [comment]
@Biplovkumar I can't reproduce that error.
I actually changed the default path to be in the Documents directory, instead of Cache directory. But this didn't lead to any error on my code, nor on the example app from this repo, that I just tried.
Could you provide more info?

**Pull request closed without merging**
