### PR TITLE
Handle images from RCT Image store

### PR DESCRIPTION
**Pull request by Almouro**
On iOS, when cropping an image with ImageEditor, it returns an uri starting with rct-image-store which could not be read by this module

### CODE REVIEW

**Comment by Almouro** [comment]
Recreated ios code from https://github.com/Almouro/generator-react-native-module, hence all the deletions/additions in code

Fixes #1

**Comment by 4ian** [comment]
Looks good to me!

BTW, I wonder if we could use RCTImageUtils (see for example [this](https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageUtils.m#L310) and [usage here](https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageEditingManager.m#L60)) to handle the scaling of the image and get rid of ImageHelpers.m/.h
Anyway, :+1:

**Comment by dangnelson** [comment]
Would love to see this merged, thanks!

**Comment by Almouro** [comment]
PR was breaking the loading of images from absolute file paths. 
I pushed force a fix, fallbacking on `initWithContentsOfFile` if the `imageLoader` included in react could not load the image

**Comment by dangnelson** [comment]
I'm also getting an extra "." before jpg, so the path reads "..jpg"

**Comment by Almouro** [comment]
Hi @dangnelson, could you give us more details? What did you try to run and what were the results you got?
Btw, is it related to this PR, or would it be a different issue?
Thanks! :)

**Pull request merged**
